### PR TITLE
Fix various issues.

### LINKED ISSUE #6: investigate `onExit` without `process.exit`
Likely this is a bug.

As @rwjblue pointed out, the fix is really just to add our own `process.on('exit')`

### PR DESCRIPTION
**Pull request by hjdivad**
See https://github.com/ember-cli/ember-cli/issues/6486

- run handlers on a natural exit
- preserve exit code when calling `process.exit` from `process.on('exit')`
- maintain node's process.exit semantics

[Fix #6]

### CODE REVIEW

**Review by rwjblue — APPROVED** [review]

File: index.js [hunk 1]
```diff
@@ -60,6 +99,9 @@ module.exports.onExit = function(cb) {
   if (!exit) {
     throw new Error('Cannot install handler when exit is not captured.  Call `captureExit()` first');
   }
+  if (isExiting) {
+    throw new Error('Cannot install handler while `onExit` handlers are running.');
```
Comment (stefanpenner) [inline index.js:113]: is this tested?

File: index.js [hunk 2]
```diff
@@ -29,6 +58,15 @@ module.exports.captureExit = function() {
   exit = process.exit;
 
   process.exit = function(code) {
+    if (handlers.length === 0 && lastTime === undefined) {
+      // synchronously exit when `process.exit` is called during a
```
Comment (stefanpenner) [inline index.js]: I believe this branch is also taken if there where just no handlers attached. The documentation implies this will only happen within an `on('exit'` hook

**Review by stefanpenner — CHANGES_REQUESTED** [review]
I'll take some time tomorrow to thoroughly review this. As i'll need to take a-bit of time to think about this unexpected issue.

File: index.js (hunk 2 above)
Comment (hjdivad) [reply index.js]: You're right.  I can update the comment.

File: index.js (hunk 1 above)
Comment (hjdivad) [reply index.js:113]: latest changes add a test for this

**Comment by hjdivad** [comment]
@stefanpenner I've responded to your issues; also I stripped the last commit b/c it didn't do what it claimed.

We should fix #9 but can do that in a separate pr and in any case it's unrelated to the ember-cli issues.

File: index.js [hunk 3]
```diff
@@ -29,6 +58,25 @@ module.exports.captureExit = function() {
...
+      //      doesn't really matter whether we take this branch or not in this
+      //      case.
+      //
+      //  2.  The process exited naturally.  We did our async work during
+      //      `beforeExit` and are in this function because someone else has
+      //      called `process.exit` during an `on('exit')` hook.  The only way
+      //      for us to preserve the exit code in this case is to exit
+      //      synchronously.
+      //
+      exit.call(process, code);
```
Comment (stefanpenner) [inline index.js]: if we have no handlers and no lastTime, should we also `return` at the end of this branch  as  I believe the flush bellow to no longer be required.

File: index.js [hunk 4]
```diff
@@ -3,6 +3,35 @@ var RSVP = require('rsvp');
...
+  var own = lastTime = module.exports._flush(lastTime, code)
+    .finally(function () {
+      // if an onExit handler has called process.exit, do not disturb
+      // `lastTime`.
+      //
+      // Otherwise, clear `lastTime` so that we know to synchronously call the
+      // real `process.exit` with the given exit code, when our captured
+      // `process.exit` is called during a `process.on('exit')` handler
+      //
+      // This is impossible to reason about, don't feel bad.  Just look at
```
Comment (stefanpenner) [inline index.js:20]: nope, seems well explained thanks

File: test.js [hunk 5]
```diff
@@ -158,6 +154,27 @@ describe('capture-exit', function() {
         exit.onExit(function () { });
       }).to.throw('Cannot install handler when exit is not captured.  Call `captureExit()` first');
     });
+
+    it('throws if an exit is already happening', function() {
```
Comment (stefanpenner) [inline test.js:158]: curious why we error, and not just flush again until no more handlers attach?

Comment (rwjblue) [reply test.js:158]: Because we can only handle this during our own `onExit` callbacks and not during `process.on('exit'` (since process.on('exit' cannot do any async).

Essentially, we are making the assumption that once we enter the "exit flow" that additional handlers cannot be added.

Comment (stefanpenner) [reply test.js:158]: Is this a constraint we are self imposing?

Comment (rwjblue) [reply test.js:158]: @stefanpenner - Yes, we are self-imposing this error (adding an additional exit handler via `captureExit.onExit` during the exit process) because it is not trivial to reason about and we can always add support back if there is a good use case presented.  I don't feel _super_ strongly that we must throw, but the specific semantics about how things would work is non-obvious.  

Try running these scripts (with the branch here):

```js
var captureExit = require('capture-exit');
captureExit.captureExit();

process.on('exit', function() {
  console.log('`process.on("exit"` firing');

  captureExit.onExit(function() {
    console.log('captureExit.onExit firing');
  });
});
console.log('exiting naturally');
```

```js
var captureExit = require('capture-exit');
captureExit.captureExit();

captureExit.onExit(function() {
  console.log('first `captureExit.onExit` firing');

  captureExit.onExit(function() {
    console.log('second `captureExit.onExit` firing');
  });
});
console.log('exiting naturally');
```

Note that in the first case, our `captureExit.onExit` handler **never** executes (this is due to node's constraint about `process.on('exit'` handlers being completely sync).

---

I think the *tldr;* summary (from my perspective) here is that this library's entire purpose is to ensure that when folks call `captureExit.onExit(function() { })` they are **guaranteed** to be ran (this is certainly ember-cli's use case, where we **must** ensure `tmp/` is cleaned).  We simply cannot guarantee that exit handlers will be run in the case of the first script in this comment.

Comment (rwjblue) [reply test.js:158]: Arguably, we could handle the second script above by changing where we set `isExiting` (because we only _really_ want to prevent the first script (`captureExit.onExit` nested inside `process.on('exit'`) but the second might be ok?).

Moving `isExiting = true` to the `.finally` inside `process.on('beforeExit'` would likely allow the second script (nested `captureExit.onExit`) and disallow the first script (`captureExit.onExit` nested inside `process.on('exit'`)...

File: index.js (hunk 3 above)
Comment (hjdivad) [reply index.js]: Fair enough although we won't get to the flush anyway since `exit` will exit.

File: test.js (hunk 5 above)
Comment (stefanpenner) [reply test.js:158]: Ah, this isn't self imposed, rather dictated by nodes requirement of sync only handles in this position

File: index.js (hunk 4 above)
Comment (hjdivad) [reply index.js:20]: Maybe I should update it to say it's only impossible for mere mortals to reason about ^_^

File: test.js (hunk 5 above)
Comment (hjdivad) [reply test.js:158]: @stefanpenner yeah the problem is that our on exit running conflates two cases: one where async is possible (`beforeExit` or during an intercepted `process.exit`) and one where async is impossible (during `process.on('exit')`).

If we want to add support to this where we can, I think we'll need to actually treat the two cases separately but I would prefer we not do that until we actually have a use case for it.

Comment (hjdivad) [reply test.js:158]: @rwjblue that might work but i think it would make things too difficult to reason about.  I would much rather we actually just have two different functions for processing handlers when async is allowed vs disallowed if we add support for this feature.

File: index.js (hunk 3 above)
Comment (hjdivad) [reply index.js]: latest push adds return here

File: test.js (hunk 5 above)
Comment (rwjblue) [reply test.js:158]: Ya, I still think throwing (as we do now) is the right answer until we have good use cases as a guide.  I was only suggesting that we _could_ possibly make the second script work (not that we _should_). 😝

**Review by stefanpenner — APPROVED** [review]
